services:

  ############## DATABASE AND VISUALIZER ##############
  postgres:
    image: postgres:17.4
    ports:
      - "5432:5432"
    volumes:
      - ./dev/db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: catalog

  pgadmin:
    image: dpage/pgadmin4:9.2.0
    ports:
      - "5050:80"
    volumes:
      - ./dev/pgadmin/servers.json:/pgadmin4/servers.json
      - ./dev/pgadmin/pgpass:/config/pgpass
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@mycomp.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    depends_on:
      - postgres

  app:
    build:
      context: .
      target: final
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGHOST: postgres
      PGPORT: 5432
      PGDATABASE: catalog